// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Chunk.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class DoubleArray;
GPB_ENUM_FWD_DECLARE(MeasurementCategory);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ChunkRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface ChunkRoot : GPBRootObject
@end

#pragma mark - DoubleArray

typedef GPB_ENUM(DoubleArray_FieldNumber) {
  DoubleArray_FieldNumber_ValuesArray = 1,
};

GPB_FINAL @interface DoubleArray : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) GPBDoubleArray *valuesArray;
/** The number of items in @c valuesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger valuesArray_Count;

@end

#pragma mark - Chunk

typedef GPB_ENUM(Chunk_FieldNumber) {
  Chunk_FieldNumber_RedsArray = 1,
  Chunk_FieldNumber_GreensArray = 2,
  Chunk_FieldNumber_BluesArray = 3,
  Chunk_FieldNumber_BlendShapeArray = 4,
  Chunk_FieldNumber_TimeStampsArray = 5,
  Chunk_FieldNumber_Fps = 6,
  Chunk_FieldNumber_Category = 7,
};

GPB_FINAL @interface Chunk : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DoubleArray*> *redsArray;
/** The number of items in @c redsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger redsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DoubleArray*> *greensArray;
/** The number of items in @c greensArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger greensArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DoubleArray*> *bluesArray;
/** The number of items in @c bluesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger bluesArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DoubleArray*> *blendShapeArray;
/** The number of items in @c blendShapeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger blendShapeArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *timeStampsArray;
/** The number of items in @c timeStampsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger timeStampsArray_Count;

@property(nonatomic, readwrite) double fps;

@property(nonatomic, readwrite) enum MeasurementCategory category;

@end

/**
 * Fetches the raw value of a @c Chunk's @c category property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Chunk_Category_RawValue(Chunk *message);
/**
 * Sets the raw value of an @c Chunk's @c category property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetChunk_Category_RawValue(Chunk *message, int32_t value);

#pragma mark - Feature

typedef GPB_ENUM(Feature_FieldNumber) {
  Feature_FieldNumber_Red = 1,
  Feature_FieldNumber_Green = 2,
  Feature_FieldNumber_Blue = 3,
  Feature_FieldNumber_BlendShape = 4,
};

GPB_FINAL @interface Feature : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) DoubleArray *red;
/** Test to see if @c red has been set. */
@property(nonatomic, readwrite) BOOL hasRed;

@property(nonatomic, readwrite, strong, null_resettable) DoubleArray *green;
/** Test to see if @c green has been set. */
@property(nonatomic, readwrite) BOOL hasGreen;

@property(nonatomic, readwrite, strong, null_resettable) DoubleArray *blue;
/** Test to see if @c blue has been set. */
@property(nonatomic, readwrite) BOOL hasBlue;

@property(nonatomic, readwrite, strong, null_resettable) DoubleArray *blendShape;
/** Test to see if @c blendShape has been set. */
@property(nonatomic, readwrite) BOOL hasBlendShape;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
