// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Category.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum MeasurementCategory

/** 测量类型 */
typedef GPB_ENUM(MeasurementCategory) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  MeasurementCategory_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 缺省值 */
  MeasurementCategory_None = 0,

  /** 心率房颤 */
  MeasurementCategory_HeartRate = 1,

  /** 血压 */
  MeasurementCategory_BloodPressure = 2,

  /** 血氧 */
  MeasurementCategory_BloodOxygen = 4,

  /** 健康风险 */
  MeasurementCategory_Risk = 8,

  /** 攻击性 */
  MeasurementCategory_Aggressivity = 16,

  /** 焦虑度 */
  MeasurementCategory_Anxiety = 32,

  /** 压抑度 */
  MeasurementCategory_Depression = 64,

  /** 活力度 */
  MeasurementCategory_Vitality = 128,

  /** 积极性 */
  MeasurementCategory_Positivity = 256,

  /** 抑郁度 */
  MeasurementCategory_Suppression = 512,

  /** 疲劳度 */
  MeasurementCategory_Fatigue = 1024,

  /** 生理测量 */
  MeasurementCategory_Physiology = 15,

  /** 情绪测量 */
  MeasurementCategory_Emotion = 1713,

  /** 全部指标 */
  MeasurementCategory_All = 1727,
};

GPBEnumDescriptor *MeasurementCategory_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL MeasurementCategory_IsValidValue(int32_t value);

#pragma mark - CategoryRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface CategoryRoot : GPBRootObject
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
