// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Report.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class BpData;
@class BpExplanation;
@class BpReport;
@class EssentialData;
@class EssentialExplanation;
@class EssentialReport;
@class HrData;
@class HrExplanation;
@class HrReport;
@class ReportIndexExplanation;
@class ReportIndexText;
@class RiskData;
@class RiskExplanation;
@class RiskReport;
@class SingleValueReport;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum Gender

typedef GPB_ENUM(Gender) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  Gender_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  Gender_Male = 0,
  Gender_Female = 1,
  Gender_Unknown = 2,
};

GPBEnumDescriptor *Gender_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Gender_IsValidValue(int32_t value);

#pragma mark - ReportRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface ReportRoot : GPBRootObject
@end

#pragma mark - Report

typedef GPB_ENUM(Report_FieldNumber) {
  Report_FieldNumber_HrReport = 1,
  Report_FieldNumber_AfReport = 2,
  Report_FieldNumber_BpReport = 3,
  Report_FieldNumber_Spo2HReport = 4,
  Report_FieldNumber_RiskReport = 5,
  Report_FieldNumber_EssentialReport = 6,
  Report_FieldNumber_PhysiologyScoreReport = 7,
  Report_FieldNumber_AggressivityReport = 8,
  Report_FieldNumber_AnxietyReport = 9,
  Report_FieldNumber_DepressionReport = 10,
  Report_FieldNumber_VitalityReport = 11,
  Report_FieldNumber_PositivityReport = 12,
  Report_FieldNumber_SuppressionReport = 13,
  Report_FieldNumber_FatigueReport = 14,
  Report_FieldNumber_MsiReport = 15,
  Report_FieldNumber_EmotionScoreReport = 16,
  Report_FieldNumber_AiReport = 17,
};

/**
 * 测量报告
 **/
GPB_FINAL @interface Report : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) HrReport *hrReport;
/** Test to see if @c hrReport has been set. */
@property(nonatomic, readwrite) BOOL hasHrReport;

@property(nonatomic, readwrite, strong, null_resettable) SingleValueReport *afReport;
/** Test to see if @c afReport has been set. */
@property(nonatomic, readwrite) BOOL hasAfReport;

@property(nonatomic, readwrite, strong, null_resettable) BpReport *bpReport;
/** Test to see if @c bpReport has been set. */
@property(nonatomic, readwrite) BOOL hasBpReport;

@property(nonatomic, readwrite, strong, null_resettable) SingleValueReport *spo2HReport;
/** Test to see if @c spo2HReport has been set. */
@property(nonatomic, readwrite) BOOL hasSpo2HReport;

@property(nonatomic, readwrite, strong, null_resettable) RiskReport *riskReport;
/** Test to see if @c riskReport has been set. */
@property(nonatomic, readwrite) BOOL hasRiskReport;

@property(nonatomic, readwrite, strong, null_resettable) EssentialReport *essentialReport;
/** Test to see if @c essentialReport has been set. */
@property(nonatomic, readwrite) BOOL hasEssentialReport;

@property(nonatomic, readwrite, strong, null_resettable) SingleValueReport *physiologyScoreReport;
/** Test to see if @c physiologyScoreReport has been set. */
@property(nonatomic, readwrite) BOOL hasPhysiologyScoreReport;

@property(nonatomic, readwrite, strong, null_resettable) SingleValueReport *aggressivityReport;
/** Test to see if @c aggressivityReport has been set. */
@property(nonatomic, readwrite) BOOL hasAggressivityReport;

@property(nonatomic, readwrite, strong, null_resettable) SingleValueReport *anxietyReport;
/** Test to see if @c anxietyReport has been set. */
@property(nonatomic, readwrite) BOOL hasAnxietyReport;

@property(nonatomic, readwrite, strong, null_resettable) SingleValueReport *depressionReport;
/** Test to see if @c depressionReport has been set. */
@property(nonatomic, readwrite) BOOL hasDepressionReport;

@property(nonatomic, readwrite, strong, null_resettable) SingleValueReport *vitalityReport;
/** Test to see if @c vitalityReport has been set. */
@property(nonatomic, readwrite) BOOL hasVitalityReport;

@property(nonatomic, readwrite, strong, null_resettable) SingleValueReport *positivityReport;
/** Test to see if @c positivityReport has been set. */
@property(nonatomic, readwrite) BOOL hasPositivityReport;

@property(nonatomic, readwrite, strong, null_resettable) SingleValueReport *suppressionReport;
/** Test to see if @c suppressionReport has been set. */
@property(nonatomic, readwrite) BOOL hasSuppressionReport;

@property(nonatomic, readwrite, strong, null_resettable) SingleValueReport *fatigueReport;
/** Test to see if @c fatigueReport has been set. */
@property(nonatomic, readwrite) BOOL hasFatigueReport;

@property(nonatomic, readwrite, strong, null_resettable) SingleValueReport *msiReport;
/** Test to see if @c msiReport has been set. */
@property(nonatomic, readwrite) BOOL hasMsiReport;

@property(nonatomic, readwrite, strong, null_resettable) SingleValueReport *emotionScoreReport;
/** Test to see if @c emotionScoreReport has been set. */
@property(nonatomic, readwrite) BOOL hasEmotionScoreReport;

@property(nonatomic, readwrite, strong, null_resettable) SingleValueReport *aiReport;
/** Test to see if @c aiReport has been set. */
@property(nonatomic, readwrite) BOOL hasAiReport;

@end

#pragma mark - SingleValueReport

typedef GPB_ENUM(SingleValueReport_FieldNumber) {
  SingleValueReport_FieldNumber_Code = 1,
  SingleValueReport_FieldNumber_Msg = 2,
  SingleValueReport_FieldNumber_Data_p = 3,
  SingleValueReport_FieldNumber_Explanation = 4,
};

GPB_FINAL @interface SingleValueReport : GPBMessage

@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;

@property(nonatomic, readwrite) double data_p;

@property(nonatomic, readwrite, strong, null_resettable) ReportIndexExplanation *explanation;
/** Test to see if @c explanation has been set. */
@property(nonatomic, readwrite) BOOL hasExplanation;

@end

#pragma mark - HrReport

typedef GPB_ENUM(HrReport_FieldNumber) {
  HrReport_FieldNumber_Code = 1,
  HrReport_FieldNumber_Msg = 2,
  HrReport_FieldNumber_Data_p = 3,
  HrReport_FieldNumber_Explanation = 4,
};

/**
 * 心率报告
 **/
GPB_FINAL @interface HrReport : GPBMessage

@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;

@property(nonatomic, readwrite, strong, null_resettable) HrData *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@property(nonatomic, readwrite, strong, null_resettable) HrExplanation *explanation;
/** Test to see if @c explanation has been set. */
@property(nonatomic, readwrite) BOOL hasExplanation;

@end

#pragma mark - BpReport

typedef GPB_ENUM(BpReport_FieldNumber) {
  BpReport_FieldNumber_Code = 1,
  BpReport_FieldNumber_Msg = 2,
  BpReport_FieldNumber_Data_p = 3,
  BpReport_FieldNumber_Explanation = 4,
};

/**
 * 血压报告
 **/
GPB_FINAL @interface BpReport : GPBMessage

@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;

@property(nonatomic, readwrite, strong, null_resettable) BpData *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@property(nonatomic, readwrite, strong, null_resettable) BpExplanation *explanation;
/** Test to see if @c explanation has been set. */
@property(nonatomic, readwrite) BOOL hasExplanation;

@end

#pragma mark - RiskReport

typedef GPB_ENUM(RiskReport_FieldNumber) {
  RiskReport_FieldNumber_Code = 1,
  RiskReport_FieldNumber_Msg = 2,
  RiskReport_FieldNumber_Data_p = 3,
  RiskReport_FieldNumber_Explanation = 4,
};

/**
 * 风险报告
 **/
GPB_FINAL @interface RiskReport : GPBMessage

@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;

@property(nonatomic, readwrite, strong, null_resettable) RiskData *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@property(nonatomic, readwrite, strong, null_resettable) RiskExplanation *explanation;
/** Test to see if @c explanation has been set. */
@property(nonatomic, readwrite) BOOL hasExplanation;

@end

#pragma mark - EssentialReport

typedef GPB_ENUM(EssentialReport_FieldNumber) {
  EssentialReport_FieldNumber_Code = 1,
  EssentialReport_FieldNumber_Msg = 2,
  EssentialReport_FieldNumber_Data_p = 3,
  EssentialReport_FieldNumber_Explanation = 4,
};

/**
 * 基础报告
 **/
GPB_FINAL @interface EssentialReport : GPBMessage

@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;

@property(nonatomic, readwrite, strong, null_resettable) EssentialData *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@property(nonatomic, readwrite, strong, null_resettable) EssentialExplanation *explanation;
/** Test to see if @c explanation has been set. */
@property(nonatomic, readwrite) BOOL hasExplanation;

@end

#pragma mark - HrData

typedef GPB_ENUM(HrData_FieldNumber) {
  HrData_FieldNumber_HrBpm = 1,
  HrData_FieldNumber_Hrv = 2,
  HrData_FieldNumber_HrConf = 3,
};

/**
 * 心率报告原始值
 **/
GPB_FINAL @interface HrData : GPBMessage

/** 心率 */
@property(nonatomic, readwrite) double hrBpm;

/** 心率变异性 */
@property(nonatomic, readwrite) double hrv;

/** 心率置信度 */
@property(nonatomic, readwrite) double hrConf;

@end

#pragma mark - HrExplanation

typedef GPB_ENUM(HrExplanation_FieldNumber) {
  HrExplanation_FieldNumber_HrBpm = 1,
  HrExplanation_FieldNumber_Hrv = 2,
};

/**
 * 心率报告解读
 **/
GPB_FINAL @interface HrExplanation : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ReportIndexExplanation *hrBpm;
/** Test to see if @c hrBpm has been set. */
@property(nonatomic, readwrite) BOOL hasHrBpm;

@property(nonatomic, readwrite, strong, null_resettable) ReportIndexExplanation *hrv;
/** Test to see if @c hrv has been set. */
@property(nonatomic, readwrite) BOOL hasHrv;

@end

#pragma mark - BpData

typedef GPB_ENUM(BpData_FieldNumber) {
  BpData_FieldNumber_BpDiastolic = 1,
  BpData_FieldNumber_BpSystolic = 2,
};

/**
 * 血压报告原始值
 **/
GPB_FINAL @interface BpData : GPBMessage

/** 舒张压 */
@property(nonatomic, readwrite) double bpDiastolic;

/** 收缩压 */
@property(nonatomic, readwrite) double bpSystolic;

@end

#pragma mark - BpExplanation

typedef GPB_ENUM(BpExplanation_FieldNumber) {
  BpExplanation_FieldNumber_BpDiastolic = 1,
  BpExplanation_FieldNumber_BpSystolic = 2,
};

/**
 * 血压报告解读
 **/
GPB_FINAL @interface BpExplanation : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ReportIndexExplanation *bpDiastolic;
/** Test to see if @c bpDiastolic has been set. */
@property(nonatomic, readwrite) BOOL hasBpDiastolic;

@property(nonatomic, readwrite, strong, null_resettable) ReportIndexExplanation *bpSystolic;
/** Test to see if @c bpSystolic has been set. */
@property(nonatomic, readwrite) BOOL hasBpSystolic;

@end

#pragma mark - RiskData

typedef GPB_ENUM(RiskData_FieldNumber) {
  RiskData_FieldNumber_BpHeartAttack = 1,
  RiskData_FieldNumber_BpStroke = 2,
  RiskData_FieldNumber_BpCvd = 3,
  RiskData_FieldNumber_BpPp = 4,
  RiskData_FieldNumber_BpTau = 5,
};

/**
 * 风险报告原始值
 **/
GPB_FINAL @interface RiskData : GPBMessage

/** 心脏病风险 */
@property(nonatomic, readwrite) double bpHeartAttack;

/** 中风风险 */
@property(nonatomic, readwrite) double bpStroke;

/** 心血管病风险 */
@property(nonatomic, readwrite) double bpCvd;

/** 心脏压力 */
@property(nonatomic, readwrite) double bpPp;

/** 血管弹性(功能) */
@property(nonatomic, readwrite) double bpTau;

@end

#pragma mark - RiskExplanation

typedef GPB_ENUM(RiskExplanation_FieldNumber) {
  RiskExplanation_FieldNumber_BpHeartAttack = 1,
  RiskExplanation_FieldNumber_BpStroke = 2,
  RiskExplanation_FieldNumber_BpCvd = 3,
  RiskExplanation_FieldNumber_BpPp = 4,
  RiskExplanation_FieldNumber_BpTau = 5,
};

/**
 * 风险报告解读
 **/
GPB_FINAL @interface RiskExplanation : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ReportIndexExplanation *bpHeartAttack;
/** Test to see if @c bpHeartAttack has been set. */
@property(nonatomic, readwrite) BOOL hasBpHeartAttack;

@property(nonatomic, readwrite, strong, null_resettable) ReportIndexExplanation *bpStroke;
/** Test to see if @c bpStroke has been set. */
@property(nonatomic, readwrite) BOOL hasBpStroke;

@property(nonatomic, readwrite, strong, null_resettable) ReportIndexExplanation *bpCvd;
/** Test to see if @c bpCvd has been set. */
@property(nonatomic, readwrite) BOOL hasBpCvd;

@property(nonatomic, readwrite, strong, null_resettable) ReportIndexExplanation *bpPp;
/** Test to see if @c bpPp has been set. */
@property(nonatomic, readwrite) BOOL hasBpPp;

@property(nonatomic, readwrite, strong, null_resettable) ReportIndexExplanation *bpTau;
/** Test to see if @c bpTau has been set. */
@property(nonatomic, readwrite) BOOL hasBpTau;

@end

#pragma mark - EssentialData

typedef GPB_ENUM(EssentialData_FieldNumber) {
  EssentialData_FieldNumber_Age = 1,
  EssentialData_FieldNumber_Gender = 2,
  EssentialData_FieldNumber_Bmi = 3,
};

/**
 * 基础数据报告原始数据
 **/
GPB_FINAL @interface EssentialData : GPBMessage

/** 年龄 */
@property(nonatomic, readwrite) int32_t age;

/** 性别 */
@property(nonatomic, readwrite) Gender gender;

/** 体重指数 */
@property(nonatomic, readwrite) double bmi;

@end

/**
 * Fetches the raw value of a @c EssentialData's @c gender property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t EssentialData_Gender_RawValue(EssentialData *message);
/**
 * Sets the raw value of an @c EssentialData's @c gender property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetEssentialData_Gender_RawValue(EssentialData *message, int32_t value);

#pragma mark - EssentialExplanation

typedef GPB_ENUM(EssentialExplanation_FieldNumber) {
  EssentialExplanation_FieldNumber_Bmi = 1,
  EssentialExplanation_FieldNumber_Age = 2,
};

/**
 * 基础数据报告解读
 **/
GPB_FINAL @interface EssentialExplanation : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ReportIndexExplanation *bmi;
/** Test to see if @c bmi has been set. */
@property(nonatomic, readwrite) BOOL hasBmi;

@property(nonatomic, readwrite, strong, null_resettable) ReportIndexExplanation *age;
/** Test to see if @c age has been set. */
@property(nonatomic, readwrite) BOOL hasAge;

@end

#pragma mark - ReportIndexExplanation

typedef GPB_ENUM(ReportIndexExplanation_FieldNumber) {
  ReportIndexExplanation_FieldNumber_IntroductionArray = 1,
  ReportIndexExplanation_FieldNumber_Risk = 2,
  ReportIndexExplanation_FieldNumber_Ranking = 3,
  ReportIndexExplanation_FieldNumber_DetailsArray = 4,
  ReportIndexExplanation_FieldNumber_AdvicesArray = 5,
};

/**
 * 报告单项指标解读
 **/
GPB_FINAL @interface ReportIndexExplanation : GPBMessage

/** AI专家解读 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *introductionArray;
/** The number of items in @c introductionArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger introductionArray_Count;

/** 风险 */
@property(nonatomic, readwrite) int32_t risk;

/** 排名(同龄人对比) */
@property(nonatomic, readwrite) double ranking;

/** 概念解释 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ReportIndexText*> *detailsArray;
/** The number of items in @c detailsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger detailsArray_Count;

/** 建议 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ReportIndexText*> *advicesArray;
/** The number of items in @c advicesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger advicesArray_Count;

@end

#pragma mark - ReportIndexText

typedef GPB_ENUM(ReportIndexText_FieldNumber) {
  ReportIndexText_FieldNumber_Name = 1,
  ReportIndexText_FieldNumber_ValuesArray = 2,
};

/**
 * 报告单项指标文本
 **/
GPB_FINAL @interface ReportIndexText : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *valuesArray;
/** The number of items in @c valuesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger valuesArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
