// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Validation.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum Validation

/** 测量校验 */
typedef GPB_ENUM(Validation) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  Validation_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 缺省值 */
  Validation_Default = 0,

  /** 未知错误 */
  Validation_UnknownError = 3001,

  /** 测量服务错误 */
  Validation_ServiceError = 3002,

  /** 服务通讯错误 */
  Validation_ServiceCommunicationError = 3003,

  /** 启动关闭的测量 */
  Validation_StartClosedMeasurement = 3004,

  /** 重复启动测量 */
  Validation_StartRepeatedly = 3005,

  /** 许可证认证失败 */
  Validation_AuthenticationFailure = 3006,

  /** 帧率过低 */
  Validation_TooLowFps = 3007,

  /** 报告测算超时 */
  Validation_ReportTimeout = 3008,

  /** 初始视频帧非法 */
  Validation_InvalidStartFrame = 3009,

  /** 图像尺寸太小 */
  Validation_TooSmallImage = 3010,

  /** 人脸丢失 */
  Validation_FaceLost = 3011,

  /** 人脸超出边界 */
  Validation_FaceOutOfBoundary = 3012,

  /** 测量距离过远或过近 */
  Validation_InappropriateDistance = 3013,

  /** 水平角度偏移 */
  Validation_YawOutOfRange = 3014,

  /** 垂直角度偏移 */
  Validation_PitchOutOfRange = 3015,

  /** 人脸晃动 */
  Validation_FaceWobble = 3016,

  /** 资源文件错误 */
  Validation_ResourceFileError = 3017,

  /** 数据输入 */
  Validation_InadequateDataInput = 3018,
};

GPBEnumDescriptor *Validation_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Validation_IsValidValue(int32_t value);

#pragma mark - ValidationRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface ValidationRoot : GPBRootObject
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
