// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Chunk.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Chunk_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Chunk_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Category.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Chunk_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Chunk_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Chunk_2eproto;
namespace Xiaoyang {
namespace Measurement {
class Chunk;
struct ChunkDefaultTypeInternal;
extern ChunkDefaultTypeInternal _Chunk_default_instance_;
class DoubleArray;
struct DoubleArrayDefaultTypeInternal;
extern DoubleArrayDefaultTypeInternal _DoubleArray_default_instance_;
class Feature;
struct FeatureDefaultTypeInternal;
extern FeatureDefaultTypeInternal _Feature_default_instance_;
}  // namespace Measurement
}  // namespace Xiaoyang
PROTOBUF_NAMESPACE_OPEN
template<> ::Xiaoyang::Measurement::Chunk* Arena::CreateMaybeMessage<::Xiaoyang::Measurement::Chunk>(Arena*);
template<> ::Xiaoyang::Measurement::DoubleArray* Arena::CreateMaybeMessage<::Xiaoyang::Measurement::DoubleArray>(Arena*);
template<> ::Xiaoyang::Measurement::Feature* Arena::CreateMaybeMessage<::Xiaoyang::Measurement::Feature>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Xiaoyang {
namespace Measurement {

// ===================================================================

class DoubleArray final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Xiaoyang.Measurement.DoubleArray) */ {
 public:
  inline DoubleArray() : DoubleArray(nullptr) {}
  ~DoubleArray() override;
  explicit constexpr DoubleArray(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DoubleArray(const DoubleArray& from);
  DoubleArray(DoubleArray&& from) noexcept
    : DoubleArray() {
    *this = ::std::move(from);
  }

  inline DoubleArray& operator=(const DoubleArray& from) {
    CopyFrom(from);
    return *this;
  }
  inline DoubleArray& operator=(DoubleArray&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DoubleArray& default_instance() {
    return *internal_default_instance();
  }
  static inline const DoubleArray* internal_default_instance() {
    return reinterpret_cast<const DoubleArray*>(
               &_DoubleArray_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DoubleArray& a, DoubleArray& b) {
    a.Swap(&b);
  }
  inline void Swap(DoubleArray* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DoubleArray* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DoubleArray* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DoubleArray>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DoubleArray& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const DoubleArray& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DoubleArray* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Xiaoyang.Measurement.DoubleArray";
  }
  protected:
  explicit DoubleArray(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValuesFieldNumber = 1,
  };
  // repeated double values = 1;
  int values_size() const;
  private:
  int _internal_values_size() const;
  public:
  void clear_values();
  private:
  double _internal_values(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_values() const;
  void _internal_add_values(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_values();
  public:
  double values(int index) const;
  void set_values(int index, double value);
  void add_values(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      values() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_values();

  // @@protoc_insertion_point(class_scope:Xiaoyang.Measurement.DoubleArray)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > values_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Chunk_2eproto;
};
// -------------------------------------------------------------------

class Chunk final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Xiaoyang.Measurement.Chunk) */ {
 public:
  inline Chunk() : Chunk(nullptr) {}
  ~Chunk() override;
  explicit constexpr Chunk(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Chunk(const Chunk& from);
  Chunk(Chunk&& from) noexcept
    : Chunk() {
    *this = ::std::move(from);
  }

  inline Chunk& operator=(const Chunk& from) {
    CopyFrom(from);
    return *this;
  }
  inline Chunk& operator=(Chunk&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Chunk& default_instance() {
    return *internal_default_instance();
  }
  static inline const Chunk* internal_default_instance() {
    return reinterpret_cast<const Chunk*>(
               &_Chunk_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Chunk& a, Chunk& b) {
    a.Swap(&b);
  }
  inline void Swap(Chunk* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Chunk* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Chunk* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Chunk>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Chunk& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Chunk& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Chunk* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Xiaoyang.Measurement.Chunk";
  }
  protected:
  explicit Chunk(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRedsFieldNumber = 1,
    kGreensFieldNumber = 2,
    kBluesFieldNumber = 3,
    kBlendShapeFieldNumber = 4,
    kTimeStampsFieldNumber = 5,
    kFpsFieldNumber = 6,
    kCategoryFieldNumber = 7,
  };
  // repeated .Xiaoyang.Measurement.DoubleArray reds = 1;
  int reds_size() const;
  private:
  int _internal_reds_size() const;
  public:
  void clear_reds();
  ::Xiaoyang::Measurement::DoubleArray* mutable_reds(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Xiaoyang::Measurement::DoubleArray >*
      mutable_reds();
  private:
  const ::Xiaoyang::Measurement::DoubleArray& _internal_reds(int index) const;
  ::Xiaoyang::Measurement::DoubleArray* _internal_add_reds();
  public:
  const ::Xiaoyang::Measurement::DoubleArray& reds(int index) const;
  ::Xiaoyang::Measurement::DoubleArray* add_reds();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Xiaoyang::Measurement::DoubleArray >&
      reds() const;

  // repeated .Xiaoyang.Measurement.DoubleArray greens = 2;
  int greens_size() const;
  private:
  int _internal_greens_size() const;
  public:
  void clear_greens();
  ::Xiaoyang::Measurement::DoubleArray* mutable_greens(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Xiaoyang::Measurement::DoubleArray >*
      mutable_greens();
  private:
  const ::Xiaoyang::Measurement::DoubleArray& _internal_greens(int index) const;
  ::Xiaoyang::Measurement::DoubleArray* _internal_add_greens();
  public:
  const ::Xiaoyang::Measurement::DoubleArray& greens(int index) const;
  ::Xiaoyang::Measurement::DoubleArray* add_greens();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Xiaoyang::Measurement::DoubleArray >&
      greens() const;

  // repeated .Xiaoyang.Measurement.DoubleArray blues = 3;
  int blues_size() const;
  private:
  int _internal_blues_size() const;
  public:
  void clear_blues();
  ::Xiaoyang::Measurement::DoubleArray* mutable_blues(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Xiaoyang::Measurement::DoubleArray >*
      mutable_blues();
  private:
  const ::Xiaoyang::Measurement::DoubleArray& _internal_blues(int index) const;
  ::Xiaoyang::Measurement::DoubleArray* _internal_add_blues();
  public:
  const ::Xiaoyang::Measurement::DoubleArray& blues(int index) const;
  ::Xiaoyang::Measurement::DoubleArray* add_blues();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Xiaoyang::Measurement::DoubleArray >&
      blues() const;

  // repeated .Xiaoyang.Measurement.DoubleArray blendShape = 4;
  int blendshape_size() const;
  private:
  int _internal_blendshape_size() const;
  public:
  void clear_blendshape();
  ::Xiaoyang::Measurement::DoubleArray* mutable_blendshape(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Xiaoyang::Measurement::DoubleArray >*
      mutable_blendshape();
  private:
  const ::Xiaoyang::Measurement::DoubleArray& _internal_blendshape(int index) const;
  ::Xiaoyang::Measurement::DoubleArray* _internal_add_blendshape();
  public:
  const ::Xiaoyang::Measurement::DoubleArray& blendshape(int index) const;
  ::Xiaoyang::Measurement::DoubleArray* add_blendshape();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Xiaoyang::Measurement::DoubleArray >&
      blendshape() const;

  // repeated int64 timeStamps = 5;
  int timestamps_size() const;
  private:
  int _internal_timestamps_size() const;
  public:
  void clear_timestamps();
  private:
  int64_t _internal_timestamps(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
      _internal_timestamps() const;
  void _internal_add_timestamps(int64_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
      _internal_mutable_timestamps();
  public:
  int64_t timestamps(int index) const;
  void set_timestamps(int index, int64_t value);
  void add_timestamps(int64_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
      timestamps() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
      mutable_timestamps();

  // double fps = 6;
  void clear_fps();
  double fps() const;
  void set_fps(double value);
  private:
  double _internal_fps() const;
  void _internal_set_fps(double value);
  public:

  // .Xiaoyang.Measurement.MeasurementCategory category = 7;
  void clear_category();
  ::Xiaoyang::Measurement::MeasurementCategory category() const;
  void set_category(::Xiaoyang::Measurement::MeasurementCategory value);
  private:
  ::Xiaoyang::Measurement::MeasurementCategory _internal_category() const;
  void _internal_set_category(::Xiaoyang::Measurement::MeasurementCategory value);
  public:

  // @@protoc_insertion_point(class_scope:Xiaoyang.Measurement.Chunk)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Xiaoyang::Measurement::DoubleArray > reds_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Xiaoyang::Measurement::DoubleArray > greens_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Xiaoyang::Measurement::DoubleArray > blues_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Xiaoyang::Measurement::DoubleArray > blendshape_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t > timestamps_;
  mutable std::atomic<int> _timestamps_cached_byte_size_;
  double fps_;
  int category_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Chunk_2eproto;
};
// -------------------------------------------------------------------

class Feature final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Xiaoyang.Measurement.Feature) */ {
 public:
  inline Feature() : Feature(nullptr) {}
  ~Feature() override;
  explicit constexpr Feature(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Feature(const Feature& from);
  Feature(Feature&& from) noexcept
    : Feature() {
    *this = ::std::move(from);
  }

  inline Feature& operator=(const Feature& from) {
    CopyFrom(from);
    return *this;
  }
  inline Feature& operator=(Feature&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Feature& default_instance() {
    return *internal_default_instance();
  }
  static inline const Feature* internal_default_instance() {
    return reinterpret_cast<const Feature*>(
               &_Feature_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Feature& a, Feature& b) {
    a.Swap(&b);
  }
  inline void Swap(Feature* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Feature* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Feature* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Feature>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Feature& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Feature& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Feature* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Xiaoyang.Measurement.Feature";
  }
  protected:
  explicit Feature(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRedFieldNumber = 1,
    kGreenFieldNumber = 2,
    kBlueFieldNumber = 3,
    kBlendShapeFieldNumber = 4,
  };
  // .Xiaoyang.Measurement.DoubleArray red = 1;
  bool has_red() const;
  private:
  bool _internal_has_red() const;
  public:
  void clear_red();
  const ::Xiaoyang::Measurement::DoubleArray& red() const;
  PROTOBUF_NODISCARD ::Xiaoyang::Measurement::DoubleArray* release_red();
  ::Xiaoyang::Measurement::DoubleArray* mutable_red();
  void set_allocated_red(::Xiaoyang::Measurement::DoubleArray* red);
  private:
  const ::Xiaoyang::Measurement::DoubleArray& _internal_red() const;
  ::Xiaoyang::Measurement::DoubleArray* _internal_mutable_red();
  public:
  void unsafe_arena_set_allocated_red(
      ::Xiaoyang::Measurement::DoubleArray* red);
  ::Xiaoyang::Measurement::DoubleArray* unsafe_arena_release_red();

  // .Xiaoyang.Measurement.DoubleArray green = 2;
  bool has_green() const;
  private:
  bool _internal_has_green() const;
  public:
  void clear_green();
  const ::Xiaoyang::Measurement::DoubleArray& green() const;
  PROTOBUF_NODISCARD ::Xiaoyang::Measurement::DoubleArray* release_green();
  ::Xiaoyang::Measurement::DoubleArray* mutable_green();
  void set_allocated_green(::Xiaoyang::Measurement::DoubleArray* green);
  private:
  const ::Xiaoyang::Measurement::DoubleArray& _internal_green() const;
  ::Xiaoyang::Measurement::DoubleArray* _internal_mutable_green();
  public:
  void unsafe_arena_set_allocated_green(
      ::Xiaoyang::Measurement::DoubleArray* green);
  ::Xiaoyang::Measurement::DoubleArray* unsafe_arena_release_green();

  // .Xiaoyang.Measurement.DoubleArray blue = 3;
  bool has_blue() const;
  private:
  bool _internal_has_blue() const;
  public:
  void clear_blue();
  const ::Xiaoyang::Measurement::DoubleArray& blue() const;
  PROTOBUF_NODISCARD ::Xiaoyang::Measurement::DoubleArray* release_blue();
  ::Xiaoyang::Measurement::DoubleArray* mutable_blue();
  void set_allocated_blue(::Xiaoyang::Measurement::DoubleArray* blue);
  private:
  const ::Xiaoyang::Measurement::DoubleArray& _internal_blue() const;
  ::Xiaoyang::Measurement::DoubleArray* _internal_mutable_blue();
  public:
  void unsafe_arena_set_allocated_blue(
      ::Xiaoyang::Measurement::DoubleArray* blue);
  ::Xiaoyang::Measurement::DoubleArray* unsafe_arena_release_blue();

  // .Xiaoyang.Measurement.DoubleArray blendShape = 4;
  bool has_blendshape() const;
  private:
  bool _internal_has_blendshape() const;
  public:
  void clear_blendshape();
  const ::Xiaoyang::Measurement::DoubleArray& blendshape() const;
  PROTOBUF_NODISCARD ::Xiaoyang::Measurement::DoubleArray* release_blendshape();
  ::Xiaoyang::Measurement::DoubleArray* mutable_blendshape();
  void set_allocated_blendshape(::Xiaoyang::Measurement::DoubleArray* blendshape);
  private:
  const ::Xiaoyang::Measurement::DoubleArray& _internal_blendshape() const;
  ::Xiaoyang::Measurement::DoubleArray* _internal_mutable_blendshape();
  public:
  void unsafe_arena_set_allocated_blendshape(
      ::Xiaoyang::Measurement::DoubleArray* blendshape);
  ::Xiaoyang::Measurement::DoubleArray* unsafe_arena_release_blendshape();

  // @@protoc_insertion_point(class_scope:Xiaoyang.Measurement.Feature)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::Xiaoyang::Measurement::DoubleArray* red_;
  ::Xiaoyang::Measurement::DoubleArray* green_;
  ::Xiaoyang::Measurement::DoubleArray* blue_;
  ::Xiaoyang::Measurement::DoubleArray* blendshape_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Chunk_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DoubleArray

// repeated double values = 1;
inline int DoubleArray::_internal_values_size() const {
  return values_.size();
}
inline int DoubleArray::values_size() const {
  return _internal_values_size();
}
inline void DoubleArray::clear_values() {
  values_.Clear();
}
inline double DoubleArray::_internal_values(int index) const {
  return values_.Get(index);
}
inline double DoubleArray::values(int index) const {
  // @@protoc_insertion_point(field_get:Xiaoyang.Measurement.DoubleArray.values)
  return _internal_values(index);
}
inline void DoubleArray::set_values(int index, double value) {
  values_.Set(index, value);
  // @@protoc_insertion_point(field_set:Xiaoyang.Measurement.DoubleArray.values)
}
inline void DoubleArray::_internal_add_values(double value) {
  values_.Add(value);
}
inline void DoubleArray::add_values(double value) {
  _internal_add_values(value);
  // @@protoc_insertion_point(field_add:Xiaoyang.Measurement.DoubleArray.values)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
DoubleArray::_internal_values() const {
  return values_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
DoubleArray::values() const {
  // @@protoc_insertion_point(field_list:Xiaoyang.Measurement.DoubleArray.values)
  return _internal_values();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
DoubleArray::_internal_mutable_values() {
  return &values_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
DoubleArray::mutable_values() {
  // @@protoc_insertion_point(field_mutable_list:Xiaoyang.Measurement.DoubleArray.values)
  return _internal_mutable_values();
}

// -------------------------------------------------------------------

// Chunk

// repeated .Xiaoyang.Measurement.DoubleArray reds = 1;
inline int Chunk::_internal_reds_size() const {
  return reds_.size();
}
inline int Chunk::reds_size() const {
  return _internal_reds_size();
}
inline void Chunk::clear_reds() {
  reds_.Clear();
}
inline ::Xiaoyang::Measurement::DoubleArray* Chunk::mutable_reds(int index) {
  // @@protoc_insertion_point(field_mutable:Xiaoyang.Measurement.Chunk.reds)
  return reds_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Xiaoyang::Measurement::DoubleArray >*
Chunk::mutable_reds() {
  // @@protoc_insertion_point(field_mutable_list:Xiaoyang.Measurement.Chunk.reds)
  return &reds_;
}
inline const ::Xiaoyang::Measurement::DoubleArray& Chunk::_internal_reds(int index) const {
  return reds_.Get(index);
}
inline const ::Xiaoyang::Measurement::DoubleArray& Chunk::reds(int index) const {
  // @@protoc_insertion_point(field_get:Xiaoyang.Measurement.Chunk.reds)
  return _internal_reds(index);
}
inline ::Xiaoyang::Measurement::DoubleArray* Chunk::_internal_add_reds() {
  return reds_.Add();
}
inline ::Xiaoyang::Measurement::DoubleArray* Chunk::add_reds() {
  ::Xiaoyang::Measurement::DoubleArray* _add = _internal_add_reds();
  // @@protoc_insertion_point(field_add:Xiaoyang.Measurement.Chunk.reds)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Xiaoyang::Measurement::DoubleArray >&
Chunk::reds() const {
  // @@protoc_insertion_point(field_list:Xiaoyang.Measurement.Chunk.reds)
  return reds_;
}

// repeated .Xiaoyang.Measurement.DoubleArray greens = 2;
inline int Chunk::_internal_greens_size() const {
  return greens_.size();
}
inline int Chunk::greens_size() const {
  return _internal_greens_size();
}
inline void Chunk::clear_greens() {
  greens_.Clear();
}
inline ::Xiaoyang::Measurement::DoubleArray* Chunk::mutable_greens(int index) {
  // @@protoc_insertion_point(field_mutable:Xiaoyang.Measurement.Chunk.greens)
  return greens_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Xiaoyang::Measurement::DoubleArray >*
Chunk::mutable_greens() {
  // @@protoc_insertion_point(field_mutable_list:Xiaoyang.Measurement.Chunk.greens)
  return &greens_;
}
inline const ::Xiaoyang::Measurement::DoubleArray& Chunk::_internal_greens(int index) const {
  return greens_.Get(index);
}
inline const ::Xiaoyang::Measurement::DoubleArray& Chunk::greens(int index) const {
  // @@protoc_insertion_point(field_get:Xiaoyang.Measurement.Chunk.greens)
  return _internal_greens(index);
}
inline ::Xiaoyang::Measurement::DoubleArray* Chunk::_internal_add_greens() {
  return greens_.Add();
}
inline ::Xiaoyang::Measurement::DoubleArray* Chunk::add_greens() {
  ::Xiaoyang::Measurement::DoubleArray* _add = _internal_add_greens();
  // @@protoc_insertion_point(field_add:Xiaoyang.Measurement.Chunk.greens)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Xiaoyang::Measurement::DoubleArray >&
Chunk::greens() const {
  // @@protoc_insertion_point(field_list:Xiaoyang.Measurement.Chunk.greens)
  return greens_;
}

// repeated .Xiaoyang.Measurement.DoubleArray blues = 3;
inline int Chunk::_internal_blues_size() const {
  return blues_.size();
}
inline int Chunk::blues_size() const {
  return _internal_blues_size();
}
inline void Chunk::clear_blues() {
  blues_.Clear();
}
inline ::Xiaoyang::Measurement::DoubleArray* Chunk::mutable_blues(int index) {
  // @@protoc_insertion_point(field_mutable:Xiaoyang.Measurement.Chunk.blues)
  return blues_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Xiaoyang::Measurement::DoubleArray >*
Chunk::mutable_blues() {
  // @@protoc_insertion_point(field_mutable_list:Xiaoyang.Measurement.Chunk.blues)
  return &blues_;
}
inline const ::Xiaoyang::Measurement::DoubleArray& Chunk::_internal_blues(int index) const {
  return blues_.Get(index);
}
inline const ::Xiaoyang::Measurement::DoubleArray& Chunk::blues(int index) const {
  // @@protoc_insertion_point(field_get:Xiaoyang.Measurement.Chunk.blues)
  return _internal_blues(index);
}
inline ::Xiaoyang::Measurement::DoubleArray* Chunk::_internal_add_blues() {
  return blues_.Add();
}
inline ::Xiaoyang::Measurement::DoubleArray* Chunk::add_blues() {
  ::Xiaoyang::Measurement::DoubleArray* _add = _internal_add_blues();
  // @@protoc_insertion_point(field_add:Xiaoyang.Measurement.Chunk.blues)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Xiaoyang::Measurement::DoubleArray >&
Chunk::blues() const {
  // @@protoc_insertion_point(field_list:Xiaoyang.Measurement.Chunk.blues)
  return blues_;
}

// repeated .Xiaoyang.Measurement.DoubleArray blendShape = 4;
inline int Chunk::_internal_blendshape_size() const {
  return blendshape_.size();
}
inline int Chunk::blendshape_size() const {
  return _internal_blendshape_size();
}
inline void Chunk::clear_blendshape() {
  blendshape_.Clear();
}
inline ::Xiaoyang::Measurement::DoubleArray* Chunk::mutable_blendshape(int index) {
  // @@protoc_insertion_point(field_mutable:Xiaoyang.Measurement.Chunk.blendShape)
  return blendshape_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Xiaoyang::Measurement::DoubleArray >*
Chunk::mutable_blendshape() {
  // @@protoc_insertion_point(field_mutable_list:Xiaoyang.Measurement.Chunk.blendShape)
  return &blendshape_;
}
inline const ::Xiaoyang::Measurement::DoubleArray& Chunk::_internal_blendshape(int index) const {
  return blendshape_.Get(index);
}
inline const ::Xiaoyang::Measurement::DoubleArray& Chunk::blendshape(int index) const {
  // @@protoc_insertion_point(field_get:Xiaoyang.Measurement.Chunk.blendShape)
  return _internal_blendshape(index);
}
inline ::Xiaoyang::Measurement::DoubleArray* Chunk::_internal_add_blendshape() {
  return blendshape_.Add();
}
inline ::Xiaoyang::Measurement::DoubleArray* Chunk::add_blendshape() {
  ::Xiaoyang::Measurement::DoubleArray* _add = _internal_add_blendshape();
  // @@protoc_insertion_point(field_add:Xiaoyang.Measurement.Chunk.blendShape)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Xiaoyang::Measurement::DoubleArray >&
Chunk::blendshape() const {
  // @@protoc_insertion_point(field_list:Xiaoyang.Measurement.Chunk.blendShape)
  return blendshape_;
}

// repeated int64 timeStamps = 5;
inline int Chunk::_internal_timestamps_size() const {
  return timestamps_.size();
}
inline int Chunk::timestamps_size() const {
  return _internal_timestamps_size();
}
inline void Chunk::clear_timestamps() {
  timestamps_.Clear();
}
inline int64_t Chunk::_internal_timestamps(int index) const {
  return timestamps_.Get(index);
}
inline int64_t Chunk::timestamps(int index) const {
  // @@protoc_insertion_point(field_get:Xiaoyang.Measurement.Chunk.timeStamps)
  return _internal_timestamps(index);
}
inline void Chunk::set_timestamps(int index, int64_t value) {
  timestamps_.Set(index, value);
  // @@protoc_insertion_point(field_set:Xiaoyang.Measurement.Chunk.timeStamps)
}
inline void Chunk::_internal_add_timestamps(int64_t value) {
  timestamps_.Add(value);
}
inline void Chunk::add_timestamps(int64_t value) {
  _internal_add_timestamps(value);
  // @@protoc_insertion_point(field_add:Xiaoyang.Measurement.Chunk.timeStamps)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
Chunk::_internal_timestamps() const {
  return timestamps_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
Chunk::timestamps() const {
  // @@protoc_insertion_point(field_list:Xiaoyang.Measurement.Chunk.timeStamps)
  return _internal_timestamps();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
Chunk::_internal_mutable_timestamps() {
  return &timestamps_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
Chunk::mutable_timestamps() {
  // @@protoc_insertion_point(field_mutable_list:Xiaoyang.Measurement.Chunk.timeStamps)
  return _internal_mutable_timestamps();
}

// double fps = 6;
inline void Chunk::clear_fps() {
  fps_ = 0;
}
inline double Chunk::_internal_fps() const {
  return fps_;
}
inline double Chunk::fps() const {
  // @@protoc_insertion_point(field_get:Xiaoyang.Measurement.Chunk.fps)
  return _internal_fps();
}
inline void Chunk::_internal_set_fps(double value) {
  
  fps_ = value;
}
inline void Chunk::set_fps(double value) {
  _internal_set_fps(value);
  // @@protoc_insertion_point(field_set:Xiaoyang.Measurement.Chunk.fps)
}

// .Xiaoyang.Measurement.MeasurementCategory category = 7;
inline void Chunk::clear_category() {
  category_ = 0;
}
inline ::Xiaoyang::Measurement::MeasurementCategory Chunk::_internal_category() const {
  return static_cast< ::Xiaoyang::Measurement::MeasurementCategory >(category_);
}
inline ::Xiaoyang::Measurement::MeasurementCategory Chunk::category() const {
  // @@protoc_insertion_point(field_get:Xiaoyang.Measurement.Chunk.category)
  return _internal_category();
}
inline void Chunk::_internal_set_category(::Xiaoyang::Measurement::MeasurementCategory value) {
  
  category_ = value;
}
inline void Chunk::set_category(::Xiaoyang::Measurement::MeasurementCategory value) {
  _internal_set_category(value);
  // @@protoc_insertion_point(field_set:Xiaoyang.Measurement.Chunk.category)
}

// -------------------------------------------------------------------

// Feature

// .Xiaoyang.Measurement.DoubleArray red = 1;
inline bool Feature::_internal_has_red() const {
  return this != internal_default_instance() && red_ != nullptr;
}
inline bool Feature::has_red() const {
  return _internal_has_red();
}
inline void Feature::clear_red() {
  if (GetArenaForAllocation() == nullptr && red_ != nullptr) {
    delete red_;
  }
  red_ = nullptr;
}
inline const ::Xiaoyang::Measurement::DoubleArray& Feature::_internal_red() const {
  const ::Xiaoyang::Measurement::DoubleArray* p = red_;
  return p != nullptr ? *p : reinterpret_cast<const ::Xiaoyang::Measurement::DoubleArray&>(
      ::Xiaoyang::Measurement::_DoubleArray_default_instance_);
}
inline const ::Xiaoyang::Measurement::DoubleArray& Feature::red() const {
  // @@protoc_insertion_point(field_get:Xiaoyang.Measurement.Feature.red)
  return _internal_red();
}
inline void Feature::unsafe_arena_set_allocated_red(
    ::Xiaoyang::Measurement::DoubleArray* red) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(red_);
  }
  red_ = red;
  if (red) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Xiaoyang.Measurement.Feature.red)
}
inline ::Xiaoyang::Measurement::DoubleArray* Feature::release_red() {
  
  ::Xiaoyang::Measurement::DoubleArray* temp = red_;
  red_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Xiaoyang::Measurement::DoubleArray* Feature::unsafe_arena_release_red() {
  // @@protoc_insertion_point(field_release:Xiaoyang.Measurement.Feature.red)
  
  ::Xiaoyang::Measurement::DoubleArray* temp = red_;
  red_ = nullptr;
  return temp;
}
inline ::Xiaoyang::Measurement::DoubleArray* Feature::_internal_mutable_red() {
  
  if (red_ == nullptr) {
    auto* p = CreateMaybeMessage<::Xiaoyang::Measurement::DoubleArray>(GetArenaForAllocation());
    red_ = p;
  }
  return red_;
}
inline ::Xiaoyang::Measurement::DoubleArray* Feature::mutable_red() {
  ::Xiaoyang::Measurement::DoubleArray* _msg = _internal_mutable_red();
  // @@protoc_insertion_point(field_mutable:Xiaoyang.Measurement.Feature.red)
  return _msg;
}
inline void Feature::set_allocated_red(::Xiaoyang::Measurement::DoubleArray* red) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete red_;
  }
  if (red) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::Xiaoyang::Measurement::DoubleArray>::GetOwningArena(red);
    if (message_arena != submessage_arena) {
      red = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, red, submessage_arena);
    }
    
  } else {
    
  }
  red_ = red;
  // @@protoc_insertion_point(field_set_allocated:Xiaoyang.Measurement.Feature.red)
}

// .Xiaoyang.Measurement.DoubleArray green = 2;
inline bool Feature::_internal_has_green() const {
  return this != internal_default_instance() && green_ != nullptr;
}
inline bool Feature::has_green() const {
  return _internal_has_green();
}
inline void Feature::clear_green() {
  if (GetArenaForAllocation() == nullptr && green_ != nullptr) {
    delete green_;
  }
  green_ = nullptr;
}
inline const ::Xiaoyang::Measurement::DoubleArray& Feature::_internal_green() const {
  const ::Xiaoyang::Measurement::DoubleArray* p = green_;
  return p != nullptr ? *p : reinterpret_cast<const ::Xiaoyang::Measurement::DoubleArray&>(
      ::Xiaoyang::Measurement::_DoubleArray_default_instance_);
}
inline const ::Xiaoyang::Measurement::DoubleArray& Feature::green() const {
  // @@protoc_insertion_point(field_get:Xiaoyang.Measurement.Feature.green)
  return _internal_green();
}
inline void Feature::unsafe_arena_set_allocated_green(
    ::Xiaoyang::Measurement::DoubleArray* green) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(green_);
  }
  green_ = green;
  if (green) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Xiaoyang.Measurement.Feature.green)
}
inline ::Xiaoyang::Measurement::DoubleArray* Feature::release_green() {
  
  ::Xiaoyang::Measurement::DoubleArray* temp = green_;
  green_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Xiaoyang::Measurement::DoubleArray* Feature::unsafe_arena_release_green() {
  // @@protoc_insertion_point(field_release:Xiaoyang.Measurement.Feature.green)
  
  ::Xiaoyang::Measurement::DoubleArray* temp = green_;
  green_ = nullptr;
  return temp;
}
inline ::Xiaoyang::Measurement::DoubleArray* Feature::_internal_mutable_green() {
  
  if (green_ == nullptr) {
    auto* p = CreateMaybeMessage<::Xiaoyang::Measurement::DoubleArray>(GetArenaForAllocation());
    green_ = p;
  }
  return green_;
}
inline ::Xiaoyang::Measurement::DoubleArray* Feature::mutable_green() {
  ::Xiaoyang::Measurement::DoubleArray* _msg = _internal_mutable_green();
  // @@protoc_insertion_point(field_mutable:Xiaoyang.Measurement.Feature.green)
  return _msg;
}
inline void Feature::set_allocated_green(::Xiaoyang::Measurement::DoubleArray* green) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete green_;
  }
  if (green) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::Xiaoyang::Measurement::DoubleArray>::GetOwningArena(green);
    if (message_arena != submessage_arena) {
      green = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, green, submessage_arena);
    }
    
  } else {
    
  }
  green_ = green;
  // @@protoc_insertion_point(field_set_allocated:Xiaoyang.Measurement.Feature.green)
}

// .Xiaoyang.Measurement.DoubleArray blue = 3;
inline bool Feature::_internal_has_blue() const {
  return this != internal_default_instance() && blue_ != nullptr;
}
inline bool Feature::has_blue() const {
  return _internal_has_blue();
}
inline void Feature::clear_blue() {
  if (GetArenaForAllocation() == nullptr && blue_ != nullptr) {
    delete blue_;
  }
  blue_ = nullptr;
}
inline const ::Xiaoyang::Measurement::DoubleArray& Feature::_internal_blue() const {
  const ::Xiaoyang::Measurement::DoubleArray* p = blue_;
  return p != nullptr ? *p : reinterpret_cast<const ::Xiaoyang::Measurement::DoubleArray&>(
      ::Xiaoyang::Measurement::_DoubleArray_default_instance_);
}
inline const ::Xiaoyang::Measurement::DoubleArray& Feature::blue() const {
  // @@protoc_insertion_point(field_get:Xiaoyang.Measurement.Feature.blue)
  return _internal_blue();
}
inline void Feature::unsafe_arena_set_allocated_blue(
    ::Xiaoyang::Measurement::DoubleArray* blue) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(blue_);
  }
  blue_ = blue;
  if (blue) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Xiaoyang.Measurement.Feature.blue)
}
inline ::Xiaoyang::Measurement::DoubleArray* Feature::release_blue() {
  
  ::Xiaoyang::Measurement::DoubleArray* temp = blue_;
  blue_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Xiaoyang::Measurement::DoubleArray* Feature::unsafe_arena_release_blue() {
  // @@protoc_insertion_point(field_release:Xiaoyang.Measurement.Feature.blue)
  
  ::Xiaoyang::Measurement::DoubleArray* temp = blue_;
  blue_ = nullptr;
  return temp;
}
inline ::Xiaoyang::Measurement::DoubleArray* Feature::_internal_mutable_blue() {
  
  if (blue_ == nullptr) {
    auto* p = CreateMaybeMessage<::Xiaoyang::Measurement::DoubleArray>(GetArenaForAllocation());
    blue_ = p;
  }
  return blue_;
}
inline ::Xiaoyang::Measurement::DoubleArray* Feature::mutable_blue() {
  ::Xiaoyang::Measurement::DoubleArray* _msg = _internal_mutable_blue();
  // @@protoc_insertion_point(field_mutable:Xiaoyang.Measurement.Feature.blue)
  return _msg;
}
inline void Feature::set_allocated_blue(::Xiaoyang::Measurement::DoubleArray* blue) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete blue_;
  }
  if (blue) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::Xiaoyang::Measurement::DoubleArray>::GetOwningArena(blue);
    if (message_arena != submessage_arena) {
      blue = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, blue, submessage_arena);
    }
    
  } else {
    
  }
  blue_ = blue;
  // @@protoc_insertion_point(field_set_allocated:Xiaoyang.Measurement.Feature.blue)
}

// .Xiaoyang.Measurement.DoubleArray blendShape = 4;
inline bool Feature::_internal_has_blendshape() const {
  return this != internal_default_instance() && blendshape_ != nullptr;
}
inline bool Feature::has_blendshape() const {
  return _internal_has_blendshape();
}
inline void Feature::clear_blendshape() {
  if (GetArenaForAllocation() == nullptr && blendshape_ != nullptr) {
    delete blendshape_;
  }
  blendshape_ = nullptr;
}
inline const ::Xiaoyang::Measurement::DoubleArray& Feature::_internal_blendshape() const {
  const ::Xiaoyang::Measurement::DoubleArray* p = blendshape_;
  return p != nullptr ? *p : reinterpret_cast<const ::Xiaoyang::Measurement::DoubleArray&>(
      ::Xiaoyang::Measurement::_DoubleArray_default_instance_);
}
inline const ::Xiaoyang::Measurement::DoubleArray& Feature::blendshape() const {
  // @@protoc_insertion_point(field_get:Xiaoyang.Measurement.Feature.blendShape)
  return _internal_blendshape();
}
inline void Feature::unsafe_arena_set_allocated_blendshape(
    ::Xiaoyang::Measurement::DoubleArray* blendshape) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(blendshape_);
  }
  blendshape_ = blendshape;
  if (blendshape) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Xiaoyang.Measurement.Feature.blendShape)
}
inline ::Xiaoyang::Measurement::DoubleArray* Feature::release_blendshape() {
  
  ::Xiaoyang::Measurement::DoubleArray* temp = blendshape_;
  blendshape_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Xiaoyang::Measurement::DoubleArray* Feature::unsafe_arena_release_blendshape() {
  // @@protoc_insertion_point(field_release:Xiaoyang.Measurement.Feature.blendShape)
  
  ::Xiaoyang::Measurement::DoubleArray* temp = blendshape_;
  blendshape_ = nullptr;
  return temp;
}
inline ::Xiaoyang::Measurement::DoubleArray* Feature::_internal_mutable_blendshape() {
  
  if (blendshape_ == nullptr) {
    auto* p = CreateMaybeMessage<::Xiaoyang::Measurement::DoubleArray>(GetArenaForAllocation());
    blendshape_ = p;
  }
  return blendshape_;
}
inline ::Xiaoyang::Measurement::DoubleArray* Feature::mutable_blendshape() {
  ::Xiaoyang::Measurement::DoubleArray* _msg = _internal_mutable_blendshape();
  // @@protoc_insertion_point(field_mutable:Xiaoyang.Measurement.Feature.blendShape)
  return _msg;
}
inline void Feature::set_allocated_blendshape(::Xiaoyang::Measurement::DoubleArray* blendshape) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete blendshape_;
  }
  if (blendshape) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::Xiaoyang::Measurement::DoubleArray>::GetOwningArena(blendshape);
    if (message_arena != submessage_arena) {
      blendshape = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, blendshape, submessage_arena);
    }
    
  } else {
    
  }
  blendshape_ = blendshape;
  // @@protoc_insertion_point(field_set_allocated:Xiaoyang.Measurement.Feature.blendShape)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Measurement
}  // namespace Xiaoyang

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Chunk_2eproto
